# Generated by Django 4.2.3 on 2023-07-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Points',
        ),
    ]
