# Generated by Django 4.2.3 on 2023-09-28 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_offer_category_offer_product_offer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
