# Generated by Django 4.2.1 on 2023-08-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_address_address_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(default="default_profile.jpg", upload_to="profile"),
        ),
    ]
