# Generated by Django 4.2.3 on 2023-09-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="alternate_number",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=models.BigIntegerField(),
        ),
    ]
