# Generated by Django 4.2.1 on 2023-08-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
