# Generated by Django 4.2.1 on 2023-09-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0011_order_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
