# Generated by Django 4.2.3 on 2023-09-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_profile_profile_image"),
        ("cart", "0013_remove_payment_created_at_remove_payment_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.address",
            ),
        ),
    ]
