# Generated by Django 4.2.3 on 2023-09-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0016_orderitem_sub_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Order placed", "Order placed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Returned"),
                ],
                default="Order Pending",
                max_length=15,
            ),
        ),
    ]
