# Generated by Django 4.2.3 on 2023-09-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sub_total',
        ),
    ]
