# Generated by Django 4.2.3 on 2023-09-16 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0018_remove_orderitem_sub_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coupon_code", models.CharField(max_length=50)),
                ("couon_price", models.IntegerField()),
                ("min_price", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
