# Generated by Django 4.2.3 on 2023-09-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0020_cart_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_price",
            field=models.BigIntegerField(default=0),
        ),
    ]
