# Generated by Django 4.2.3 on 2023-09-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0021_order_coupon_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="offer",
            field=models.BigIntegerField(default=0),
        ),
    ]
