# Generated by Django 4.2.3 on 2023-09-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0022_order_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
